# =====================================================================================
# profile
# =====================================================================================
spring.profiles.active=@profileActive@

# =====================================================================================
# app-name
# =====================================================================================
spring.application.name=@project.name@

# =====================================================================================
# server
# =====================================================================================
server.port=7070
server.tomcat.uri-encoding=UTF-8
# 配置 SameSite 为 None，支持跨站点 Cookie
#server.servlet.session.cookie.http-only=false
#server.servlet.session.cookie.same-site=None
#server.servlet.session.cookie.secure=true
server.servlet.session.cookie.name=csession-${spring.application.name}
server.servlet.session.persistent=true
# 启用 HTTPS
server.ssl.enabled=true
server.ssl.key-store=C:/Dev/projects/jee/chok2-examples/oauth2-client-server/src/main/resources/localhost.p12
#server.ssl.key-store=classpath:localhost.p12
server.ssl.key-store-password=888888
server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=your-alias

server.error.include-message=always
server.error.include-binding-errors=always

# =====================================================================================
# I18n 配置
## =====================================================================================
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8

# =====================================================================================
# Log 配置
# =====================================================================================
logging.config=classpath:logback-spring.xml

# =====================================================================================
# Redis 配置
# =====================================================================================
## Redis数据库索引（默认为0）
spring.data.redis.database=0
## Redis服务器地址
spring.data.redis.host=127.0.0.1
## Redis服务器连接端口
spring.data.redis.port=6379
## Redis服务器连接密码（默认为空）
spring.data.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active=-1
## 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1
## 连接池中的最大空闲连接
spring.redis.jedis.pool.max-idle=10
## 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=1
## 连接超时时间（毫秒）
spring.data.redis.timeout=6000

# =====================================================================================
# OAuth2 Client 配置
# =====================================================================================
spring.security.oauth2.client.registration.rico-client-oidc.provider=spring
spring.security.oauth2.client.registration.rico-client-oidc.client-id=rico-client
spring.security.oauth2.client.registration.rico-client-oidc.client-secret=321
spring.security.oauth2.client.registration.rico-client-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.rico-client-oidc.redirect-uri=https://oauth2-client-server:7070/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.rico-client-oidc.scope=openid,profile,test.read
spring.security.oauth2.client.registration.rico-client-oidc.client-name=rico-client-oidc

spring.security.oauth2.client.registration.rico-client-authorization-code.provider=spring
spring.security.oauth2.client.registration.rico-client-authorization-code.client-id=rico-client
spring.security.oauth2.client.registration.rico-client-authorization-code.client-secret=321
spring.security.oauth2.client.registration.rico-client-authorization-code.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.rico-client-authorization-code.redirect-uri=https://oauth2-client-server:7070/authorized
spring.security.oauth2.client.registration.rico-client-authorization-code.scope=message.read,message.write,test.read
spring.security.oauth2.client.registration.rico-client-authorization-code.client-name=rico-client-authorization-code

spring.security.oauth2.client.provider.spring.issuer-uri=http://oauth2-auth-server:9000

spring.cloud.gateway.mvc.routes[0].id=userinfo
spring.cloud.gateway.mvc.routes[0].uri=http://oauth2-auth-server:9000
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/userinfo
spring.cloud.gateway.mvc.routes[0].filters[0]=TokenRelay=
#
#spring.cloud.gateway..mvc.routes[1].id=demo
#spring.cloud.gateway.mvc.routes[1].uri=http://oauth2-resource-server:8090
#spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v3_1/customtbdemo/getList
#spring.cloud.gateway.mvc.routes[1].filters[0]=RelayTokenIfExists=rico-client-oidc
##spring.cloud.gateway.mvc.routes[1].filters[0]=RelayTokenIfExists=rico-client-authorization-code

#app.base-uri=https://ui-server:8848/
app.base-uri=https://oauth2-client-server:8848/
