# =====================================================================================
# profile
# =====================================================================================
spring.profiles.active=@profileActive@

# =====================================================================================
# app-name
# =====================================================================================
spring.application.name=@project.name@

# =====================================================================================
# server
# =====================================================================================
server.port=9000
server.tomcat.uri-encoding=UTF-8
server.servlet.session.cookie.name=csession-${spring.application.name}
server.servlet.session.persistent=true

server.error.include-message=always
server.error.include-binding-errors=always

# =====================================================================================
# I18n 配置
## =====================================================================================
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
  
# =====================================================================================
# Log 配置
# =====================================================================================
logging.config=classpath:logback-spring.xml

# =====================================================================================
# Redis 配置
# =====================================================================================
## Redis数据库索引（默认为0）
spring.redis.database=0
## Redis服务器地址
spring.redis.host=127.0.0.1
## Redis服务器连接端口
spring.redis.port=6379
## Redis服务器连接密码（默认为空）
spring.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active=-1
## 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1
## 连接池中的最大空闲连接
spring.redis.jedis.pool.max-idle=10
## 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=1
## 连接超时时间（毫秒）
spring.redis.timeout=6000

# =====================================================================================
# Auth 配置
# =====================================================================================
auth.issuer=http://oauth2-auth-server:9000
auth.login-page=/auth/forward
auth.login-processing-url=/auth/process


management.tracing.enabled=true
management.tracing.sampling.probability=1.0


#spring.security.user.name=user
#spring.security.user.password=password
#
#spring.security.oauth2.authorizationserver.client.rico-client.registration.client-id=rico-client
#spring.security.oauth2.authorizationserver.client.rico-client.registration.client-secret={noop}321
#spring.security.oauth2.authorizationserver.client.rico-client.registration.client-authentication-methods=client_secret_basic
#spring.security.oauth2.authorizationserver.client.rico-client.registration.authorization-grant-types=authorization_code,refresh_token,client_credentials
#spring.security.oauth2.authorizationserver.client.rico-client.registration.redirect-uris=https://oauth2-client-server:7070/login/oauth2/code/rico-client-oidc,https://oauth2-client-server:7070/authorized,https://ui-server:8848/oauth2callback-standard
#spring.security.oauth2.authorizationserver.client.rico-client.registration.post-logout-redirect-uris=https://oauth2-client-server:7070/logout
##spring.security.oauth2.authorizationserver.client.rico-client.registration.post-logout-redirect-uris=http://oauth2-client-server:8080/logged-out
#spring.security.oauth2.authorizationserver.client.rico-client.registration.scopes=openid,profile,message.read,message.write,test.read
#spring.security.oauth2.authorizationserver.client.rico-client.require-authorization-consent=false
