# =====================================================================================
# Datasource auth
# =====================================================================================
# Info
datasource.mybatis.auth.driver-class-name = oracle.jdbc.OracleDriver
datasource.mybatis.auth.url=jdbc:oracle:thin:@10.12.204.152:1521:orcl
datasource.mybatis.auth.username=epomrp
datasource.mybatis.auth.password=epomrp
# Pool
datasource.mybatis.auth.minimumIdle=10
datasource.mybatis.auth.maximumPoolSize=100
# 最大存活时间，60秒
datasource.mybatis.auth.maxLifetime=60000
# 空闲超时，30秒
datasource.mybatis.auth.idleTimeout=30000  
datasource.mybatis.auth.mapper-location=classpath*:com/**/mapper/*.xml

# =====================================================================================
# Mybatis config
# =====================================================================================
mybatis.config-location=classpath:mybatis.xml